name: SimpleHome
version: '${version}'
main: fi.makelord95.simplehome.SimpleHome
api-version: '1.20'
author: Makelord95
description: Simple home plugin

permissions:
  simplehome.home:
    description: Teleport to your home
    default: true

  simplehome.sethome:
    description: Set your home
    default: true


commands:
  home:
    description: Teleport to your home
    usage: /home
    permission: simplehome.home

  sethome:
    description: Set your home
    usage: /sethome
    permission: simplehome.sethome
